on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@master
      # Run your project's build step
      # - name: Build
      #   run: npm install && npm run build
      
      - name: use Node.js
        uses: actions/setup-node@v1
        with:
            node-vertion:10
        
      - name:npm install and build
        run:|
          npm install
          npm run build
        
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: AysaQAQ # e.g. 'my-project'
          directory: docs/.vuepress/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}