on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v3
          with:
              node-version:16
              cache:npm
        - run: npm install
        
        - name: Build
          run: npm run docs:build
        
        - name: Publish
          uses: cloudflare/pages-action@1
          with:
              apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              projectName: AysaQAQ # e.g. 'my-project'
              directory: docs/.vuepress/dist
              gitHubToken: ${{ secrets.GITHUB_TOKEN }}